name: core_location
description: Background location tracking and telemetry engine for Rumbo Fino drivers
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
